# Generated by Django 3.2.2 on 2021-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20210513_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
