# Generated by Django 3.2.2 on 2025-07-04 15:11

from django.db import migrations, models
import src.apps.brand.models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_auto_20241006_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.CharField(default=src.apps.brand.models.generate_uuid_hex, max_length=32, primary_key=True, serialize=False),
        ),
    ]
