# Generated by Django 3.2.2 on 2021-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
