# Generated by Django 3.2.2 on 2021-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
