# Generated by Django 3.2.2 on 2021-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20210912_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
