# Generated by Django 3.2.2 on 2021-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_place_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
