# Generated by Django 3.2.2 on 2022-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_alter_hashtag_created_at'),
        ('place', '0010_alter_place_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='hashtag.Hashtag'),
        ),
    ]
