# Generated by Django 3.2.2 on 2022-01-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_alter_place_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
