# Generated by Django 3.2.2 on 2022-03-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
        ('brand', '0006_auto_20210727_2325'),
        ('place', '0012_auto_20220118_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='brand',
            field=models.ForeignKey(db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_places', related_query_name='create_place', to='user.user'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_places', related_query_name='update_place', to='user.user'),
        ),
    ]
